origins:
  - owner: temporalio
    repo: money-transfer-project-template-dotnet
  - owner: temporalio
    repo: money-transfer-project-template-python
  - owner: temporalio
    repo: money-transfer-project-template-java
  - owner: temporalio
    repo: hello-world-project-template-java
  - owner: temporalio
    repo: money-transfer-project-template-ts
  - owner: temporalio
    repo: money-transfer-project-template-go
  - owner: temporalio
    repo: hello-world-project-template-go
  - owner: temporalio
    repo: subscription-workflow-project-template-go
  - owner: temporalio
    repo: subscription-workflow-project-template-java
  - owner: temporalio
    repo: subscription-workflow-project-template-typescript
  - owner: temporalio
    repo: subscription-workflow-project-template-php
  - owner: temporalio
    repo: temporal
  - owner: temporalio
    repo: samples-php
  - owner: temporalio
    repo: hello-world-project-template-python
  - owner: temporalio
    repo: samples-typescript
  # Some samples were left in the SDK code itself because it has better testing
  # capabilities than the samples repo
  - owner: temporalio
    repo: sdk-typescript
  - owner: temporalio
    repo: samples-go
  - owner: temporalio
    repo: samples-java
  - owner: temporalio
    repo: temporal-ecommerce
  - owner: temporalio
    repo: background-checks
  - owner: temporalio
    repo: email-subscription-project-go
  - owner: temporalio
    repo: data-pipeline-project-python
  - owner: temporalio
    repo: email-subscription-project-python
  - files: 
      pattern: './docs/tutorials/go/background-check/code/**/*.go'
      owner: 'temporalio'
      repo: 'temporal-learning'
      ref: 'main'
  - files: 
      pattern: './docs/tutorials/python/background-check/code/**/*.py'
      owner: 'temporalio'
      repo: 'temporal-learning'
      ref: 'main'
  - files: 
      pattern: './docs/tutorials/typescript/background-check/code/**/*.ts'
      owner: 'temporalio'
      repo: 'temporal-learning'
      ref: 'main'
  - files: 
      pattern: './docs/tutorials/java/background-check/code/**/*.java'
      owner: 'temporalio'
      repo: 'temporal-learning'
      ref: 'main'

targets:
  - docs/tutorials
  - docs/getting_started
  - docs/examples

features:
  enable_source_link: true
  enable_code_block: true
  allowed_target_extensions: [.md, .mdx]
